"""add phone number to users table

Revision ID: 417abdef7bb6
Revises: 4360ffd6d75f
Create Date: 2023-01-28 16:42:41.604358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417abdef7bb6'
down_revision = '4360ffd6d75f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
